versions: 2.1

jobs:
  build: # name of your job
    docker: # executor type
      - image: cimg/base:stable # primary container will run the latest, production-ready base image
    steps:
      # Commands run in the primary container
      - echo "aa"
